export const LOGIN_CLICKED = "LOGIN_CLICKED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGIN_ATTEMPTED = "LOGIN_ATTEMPTED";
export const ENVIRONMENT_CLICKED = "ENVIRONMENT_CLICKED";
export const LODING_ENVIRONMENT = "LODING_ENVIRONMENT";
export const ENVIRONMENT_SUCCESS = "ENVIRONMENT_SUCCESS";
export const ENVIRONMENT_FAILED = "ENVIRONMENT_FAILED";
